[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
stderr_logfile=/var/log/php-fpm.err.log
stdout_logfile=/var/log/php-fpm.out.log
autostart=true
autorestart=true
priority=999
startsecs=10
stopwaitsecs=10

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log
autostart=true
autorestart=true
priority=998
startsecs=5
stopwaitsecs=10

[group:webserver]
programs=php-fpm,nginx
